# generated by datamodel-codegen:
#   filename:  add-role.json
#   timestamp: 2023-05-03T08:43:53+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Body(BaseModel):
    users: List[str]


class User(BaseModel):
    user_id: str
    name: str
    email: str


class Credentials(BaseModel):
    jti: str


class Auth(BaseModel):
    user: User
    strategy: str
    credentials: Credentials


class Request(BaseModel):
    method: str
    path: str
    query: Dict[str, Any]
    userAgent: str
    body: Body
    channel: str
    ip: str
    auth: Auth


class Response(BaseModel):
    statusCode: int
    body: Dict[str, Any]


class Details(BaseModel):
    request: Request
    response: Response


class Model(BaseModel):
    date: str
    type: str
    description: str
    client_id: str
    client_name: str
    ip: str
    user_agent: str
    details: Details
    user_id: str
    log_id: str
    field_id: str = Field(..., alias='_id')
    isMobile: bool
    id: str
